# Created by: Shane Ambler <FreeBSD@Shaneware.biz>
# $FreeBSD$

PORTNAME=	pyffi
PORTVERSION=	2.2.2
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
DISTFILES=	PyFFI-${PORTVERSION}${EXTRACT_SUFX}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	Python File Format Interface

LICENSE=	BSD

USES=		python:3.3+ zip
USE_PYTHON=	autoplist distutils concurrent
NO_ARCH=	yes
WRKSRC=		${WRKDIR}/PyFFI-${PORTVERSION}

.include <bsd.port.mk>
