# Created by: Shane Ambler
# $FreeBSD$

PORTNAME=	fuzzywuzzy
PORTVERSION=	0.8.0
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	Fuzzy string matching in python

LICENSE=	MIT

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}levenshtein>0:devel/py-levenshtein

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
