--- intern/ffmpeg/ffmpeg_compat.h.orig	2017-01-13 13:44:18 UTC
+++ intern/ffmpeg/ffmpeg_compat.h
@@ -48,6 +48,46 @@
 
 #include <libswscale/swscale.h>
 
+#if (LIBAVFORMAT_VERSION_MAJOR > 56)
+
+#define avcodec_alloc_frame av_frame_alloc
+#define avcodec_free_frame av_frame_free
+#define avcodec_get_frame_defaults av_frame_unref
+#define avcodec_encode_video avcodec_encode_video2
+
+#define PIX_FMT_ARGB AV_PIX_FMT_ARGB
+#define PIX_FMT_BGR32 AV_PIX_FMT_BGR32
+#define PIX_FMT_BGR32_1 AV_PIX_FMT_BGR32_1
+#define PIX_FMT_RGBA AV_PIX_FMT_RGBA
+#define PIX_FMT_RGB24 AV_PIX_FMT_RGB24
+#define PIX_FMT_RGB32 AV_PIX_FMT_RGB32
+#define PIX_FMT_RGB32_1 AV_PIX_FMT_RGB32_1
+#define PIX_FMT_YUV420P AV_PIX_FMT_YUV420P
+#define PIX_FMT_YUV422P AV_PIX_FMT_YUV422P
+#define PIX_FMT_YUVJ420P AV_PIX_FMT_YUV420P
+
+#define CODEC_ID_AAC AV_CODEC_ID_AAC
+#define CODEC_ID_AC3 AV_CODEC_ID_AC3
+#define CODEC_ID_VORBIS AV_CODEC_ID_VORBIS
+#define CODEC_ID_FLV1 AV_CODEC_ID_FLV1
+#define CODEC_ID_H264 AV_CODEC_ID_H264
+#define CODEC_ID_HUFFYUV AV_CODEC_ID_HUFFYUV
+#define CODEC_ID_FFV1 AV_CODEC_ID_FFV1
+#define CODEC_ID_QTRLE AV_CODEC_ID_QTRLE
+#define CODEC_ID_PNG AV_CODEC_ID_PNG
+#define CODEC_ID_THEORA AV_CODEC_ID_THEORA
+#define CODEC_ID_DVVIDEO AV_CODEC_ID_DVVIDEO
+#define CODEC_ID_MPEG1VIDEO AV_CODEC_ID_MPEG1VIDEO
+#define CODEC_ID_MPEG2VIDEO AV_CODEC_ID_MPEG2VIDEO
+#define CODEC_ID_MPEG4 AV_CODEC_ID_MPEG4
+#define CODEC_ID_MP3 AV_CODEC_ID_MP3
+#define CODEC_ID_NONE AV_CODEC_ID_NONE
+#define CODEC_ID_PCM_S16LE AV_CODEC_ID_PCM_S16LE
+#define CODEC_ID_DNXHD AV_CODEC_ID_DNXHD
+#define CODEC_ID_MJPEG AV_CODEC_ID_MJPEG
+
+#endif
+
 #if (LIBAVFORMAT_VERSION_MAJOR > 52) || ((LIBAVFORMAT_VERSION_MAJOR >= 52) && (LIBAVFORMAT_VERSION_MINOR >= 105))
 #define FFMPEG_HAVE_AVIO 1
 #endif
