# Created by: Shane Ambler
# $FreeBSD$

PORTNAME=	odfpy
PORTVERSION=	1.3.2
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	Python API and tools to manipulate OpenDocument files

LICENSE=	APACHE20 GPLv2
LICENSE_COMB=	dual

USES=		python
USE_PYTHON=	autoplist concurrent distutils
NO_ARCH=	yes

.include <bsd.port.mk>
