# Created by: Shane Ambler
# $FreeBSD$

PORTNAME=	pyscroll
PORTVERSION=	2.16.2
CATEGORIES=	graphics python devel
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	Scrolling maps library for pygame

LICENSE=	LGPL3

USES=		python zip
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
