# Created by: Shane Ambler
# $FreeBSD$

PORTNAME=	vispy
PORTVERSION=	0.4.0
CATEGORIES=	graphics python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	High-performance data visualization library

LICENSE=	BSD

RUN_DEPENDS=	${PYNUMPY}

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
