# Created by: Shane Ambler
# $FreeBSD$

CATEGORIES=	graphics multimedia python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

COMMENT=	OpenImageIO python bindings

MASTERDIR=	${.CURDIR}/../openimageio
# we need to use the same options as the main port
OPTIONS_NAME=	graphics_openimageio

.include "${MASTERDIR}/Makefile"
