# Created by: Shane Ambler <FreeBSD@Shaneware.biz>
# $FreeBSD$

PORTNAME=	openid
PORTVERSION=	3.0.2
CATEGORIES=	security python
MASTER_SITES=	GH
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

USE_GITHUB=	yes
GH_ACCOUNT=	necaris
GH_PROJECT=	python3-openid
GH_TAGNAME=	v${PORTVERSION}
GH_COMMIT=	d384d34

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	Python OpenID support for python3

USE_PYTHON=	3
USE_PYDISTUTILS=yes
PYDISTUTILS_AUTOPLIST=	yes
PYTHON_CONCURRENT_INSTALL=yes

.include <bsd.port.mk>
