# Created by: Shane Ambler <FreeBSD@Shaneware.biz>
# $FreeBSD$

PORTNAME=	sambler-desktop-py32
PORTVERSION=	2
CATEGORIES=	misc
MASTER_SITES=	# Empty
DISTFILES=	# None

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	LOCAL py32 Metaport for building my software

BUILD_DEPENDS=	pkg:${PORTSDIR}/ports-mgmt/pkg
LIB_DEPENDS=	# Empty so subsequent LIB_DEPENDS need +=
RUN_DEPENDS=	# Empty so subsequent RUN_DEPENDS need +=
.include <portslist>

NO_BUILD=	yes
USE_PYTHON=	3.2
NO_MTREE=	yes

do-install:	# empty

.include <bsd.port.mk>
