# Created by: Shane Ambler
# $FreeBSD$

PORTNAME=	pytmx
PORTVERSION=	3.20.14
CATEGORIES=	graphics python devel
MASTER_SITES=	CHEESESHOP
DISTNAME=	PyTMX-${PORTVERSION}${DISTVERSIONSUFFIX}
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	TMX map loader designed for games

LICENSE=	LGPL3

USES=		python zip
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
