# Created by: lightside <lightside@gmx.com>
# $FreeBSD$

PKGNAMESUFFIX=	-tools

COMMENT=	Game integrated development environment

OPTIONS_EXCLUDE=	#
OPTIONS_SLAVE=	TOOLS

MASTERDIR=	${.CURDIR}/../godot

.include "${MASTERDIR}/Makefile"
