# Created by: lightside <lightside@gmx.com>
# $FreeBSD$

PKGNAMESUFFIX=	-tools

COMMENT=	Game development environment

MASTERDIR=	${.CURDIR}/../godot

OPTIONS_DEFINE=		EXAMPLES

.include "${MASTERDIR}/Makefile"
