# Created by: Shane Ambler <FreeBSD@Shaneware.biz>
# $FreeBSD$

PORTNAME=	python3-openid
PORTVERSION=	3.1.0
CATEGORIES=	security python
#MASTER_SITES=	GH
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	Python OpenID for python3

LICENSE=	APACHE20

CONFLICTS=	${PYTHON_PKGNAMEPREFIX}python-openid

USES=		python:3.4+
USE_PYTHON= autoplist concurrent distutils
NO_ARCH=	yes

.include <bsd.port.mk>
