# Created by: Shane Ambler
# $FreeBSD$

PORTNAME=	jsondatabase
PORTVERSION=	0.1.1
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	Flat file database for json objects

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
