--- build_files/cmake/Modules/FindOpenImageIO.cmake.orig	2019-08-02 08:33:57 UTC
+++ build_files/cmake/Modules/FindOpenImageIO.cmake
@@ -40,7 +40,7 @@ SET(_openimageio_SEARCH_DIRS
 
 FIND_PATH(OPENIMAGEIO_INCLUDE_DIR
   NAMES
-    OpenImageIO/imageio.h
+    OpenImageIO18/imageio.h
   HINTS
     ${_openimageio_SEARCH_DIRS}
   PATH_SUFFIXES
@@ -49,7 +49,7 @@ FIND_PATH(OPENIMAGEIO_INCLUDE_DIR
 
 FIND_LIBRARY(OPENIMAGEIO_LIBRARY
   NAMES
-    OpenImageIO
+    OpenImageIO18
   HINTS
     ${_openimageio_SEARCH_DIRS}
   PATH_SUFFIXES
@@ -58,7 +58,7 @@ FIND_LIBRARY(OPENIMAGEIO_LIBRARY
 
 FIND_FILE(OPENIMAGEIO_IDIFF
   NAMES
-    idiff
+    idiff18
   HINTS
     ${_openimageio_SEARCH_DIRS}
   PATH_SUFFIXES
@@ -71,10 +71,12 @@ INCLUDE(FindPackageHandleStandardArgs)
 FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenImageIO DEFAULT_MSG
     OPENIMAGEIO_LIBRARY OPENIMAGEIO_INCLUDE_DIR)
 
+SET(OPENIMAGEIO_FOUND $OPENIMAGEIO18_FOUND)
+
 IF(OPENIMAGEIO_FOUND)
   SET(OPENIMAGEIO_LIBRARIES ${OPENIMAGEIO_LIBRARY})
   SET(OPENIMAGEIO_INCLUDE_DIRS ${OPENIMAGEIO_INCLUDE_DIR})
-  IF(EXISTS ${OPENIMAGEIO_INCLUDE_DIR}/OpenImageIO/pugixml.hpp)
+  IF(EXISTS ${OPENIMAGEIO_INCLUDE_DIR}/OpenImageIO18/pugixml.hpp)
     SET(OPENIMAGEIO_PUGIXML_FOUND TRUE)
   ELSE()
     SET(OPENIMAGEIO_PUGIXML_FOUND FALSE)
