# Created by: Shane Ambler <FreeBSD@Shaneware.biz>
# $FreeBSD$

PORTNAME=	typing
PORTVERSION=	3.5.1.0
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	standard library typing module for older python versions

LICENSE=	PSFL

USES=		python:-3.4
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
