# Created by: Shane Ambler <FreeBSD@Shaneware.biz>
# $FreeBSD$

PORTNAME=	sambler-blender-render
PORTVERSION=	3
CATEGORIES=	misc
MASTER_SITES=	# Empty
DISTFILES=	# None

MAINTAINER=	FreeBSD@Shaneware.biz
COMMENT=	LOCAL Metaport for building my software

BUILD_DEPENDS=	# Empty so subsequent BUILD_DEPENDS need +=
LIB_DEPENDS=	# Empty so subsequent LIB_DEPENDS need +=
RUN_DEPENDS=	# Empty so subsequent RUN_DEPENDS need +=
.include <portslist>

NO_BUILD=	yes
USES= python:2.7
NO_MTREE=	yes

do-install:	# empty

.include <bsd.port.mk>
